export const VALID_CARDS = [
  'Action News Crew',
  'Agent Bishop, Man in Black',
  'All Will Be One',
  'Anchovy & Banana Pizza',
  "April O'Neil, Hacktivist",
  "April O'Neil, Kunoichi Trainee",
  'April, Reporter of the Weird',
  'Arcbound Ravager',
  'Armaggon, Future Shark',
  'Ashcoat of the Shadow Swarm',
  'Baxter Stockman',
  'Bebop & Rocksteady',
  'Bebop, Warthog Warrior',
  'Bespoke B?',
  'Bot Bashing Time',
  'Brainstorm',
  'Brilliance Unleashed',
  'Broadcast Takeover',
  'Buzz Bots',
  'Casey Jones, Jury-Rig Justiciar',
  'Casey Jones, Vigilante',
  'Chrome Dome',
  "Conqueror's Flail",
  'Cool but Rude',
  'Courier of Comestibles',
  'Cowabunga!',
  'Crustacean Commando',
  'Cytoplast Manipulator',
  'Dark Leo & Shredder',
  'Death in the Family',
  'Dimension X',
  'Dimensional Exile',
  'Does Machines',
  'Don & Leo, Problem Solvers',
  'Don & Raph, Hard Science',
  "Donatello's Technique",
  'Donatello, Gadget Master',
  'Donatello, Mutant Mechanic',
  'Donatello, Turtle Techie',
  'Donatello, Way with Machines',
  'Doubling Season',
  'Dream Beavers',
  'EPF Point Squad',
  'East Wind Avatar',
  'Escape Tunnel',
  'Everything Pizza',
  'Featherbrained Filcher',
  'Foot Elite',
  'Foot Headquarters',
  'Foot Mystic',
  'Foot Ninjas',
  'Forest',
  'Frog Butler',
  'Fugitive Droid',
  'General Traag, Heart of Stone',
  'Genghis Frog',
  'Go Ninja Go',
  'Groundchuck & Dirtbag',
  'Grounded for Life',
  'Guac & Marshmallow Pizza',
  'Hamato Guardian Stance',
  'Hard-Won Jitte',
  'Henchbots',
  'High-Flying Ace',
  'Ice Cream Kitty',
  'Illegitimate Business',
  'Improvised Arsenal',
  'Insectoid Exterminator',
  'Island',
  "Jennika's Technique",
  'Jennika, Bad Apple Big Sister',
  "Karai's Technique",
  'Karai, Future of the Foot',
  "Kitsune's Technique",
  "Kitsune, Dragon's Daughter",
  'Koya, Death from Above',
  'Krang & Shredder',
  'Krang, Master Mind',
  'Krang, Utrom Warlord',
  "Leader's Talent",
  'Leatherhead, Swamp Stalker',
  "Leonardo's Technique",
  'Leonardo, Big Brother',
  'Leonardo, Cutting Edge',
  'Leonardo, Leader in Blue',
  'Leonardo, Sewer Samurai',
  'Lessons from Life',
  'Lita, Little Orphan Amphibian',
  'Lord Dregg, Insect Invader',
  'Madame Null, Power Broker',
  'Make Your Move',
  'Manhole Missile',
  'Mechanized Ninja Cavalry',
  'Metalhead',
  'Metallic Mimic',
  "Michelangelo's Technique",
  'Michelangelo, Game Master',
  'Michelangelo, Improviser',
  'Michelangelo, Mutant BFF',
  'Michelangelo, Weirdness to 11',
  'Mighty Mutanimals',
  'Mikey & Don, Party Planners',
  'Mikey & Leo, Chaos & Order',
  'Mind Transfer Protocol',
  'Mona Lisa, Science Geek',
  'Mondo Gecko',
  'Mountain',
  'Mouser Attack!',
  'Mouser Foundry',
  'Mouser Mark III',
  'Mutagen Man, Living Ooze',
  'Mutant Chain Reaction',
  'Mutant Town',
  'Mutant Town Musicians',
  'Negate',
  "New Generation's Technique",
  'Ninja Teen',
  'Nobody',
  'North Wind Avatar',
  'Northampton Farm',
  'Novel Nunchaku',
  'Null Group Biological Assets',
  'Old Hob, Alleycat Blues',
  'Omni-Cheese Pizza',
  'Ooze Spill',
  'Oroku Saki, Shredder Rising',
  'Pain 101',
  'Paramecia Coloniex',
  'Party Dude',
  'Path to Exile',
  'Pizza Face, Gastromancer',
  'Plague of Vermin',
  'Plains',
  'Prehistoric Pet',
  'Primordial Pachyderm',
  'Punk Frogs',
  'Purple Dragon Punks',
  'Putrid Pals',
  'Quintessential Katana',
  'Ragamuffin Raptor',
  'Raph & Leo, Sibling Rivals',
  'Raph & Mikey, Troublemakers',
  "Raphael's Technique",
  'Raphael, Most Attitude',
  'Raphael, Ninja Destroyer',
  'Raphael, Tough Turtle',
  'Raphael, the Nightwatcher',
  'Rat King, Verminister',
  'Ravenous Robots',
  'Ray Fillet, Man Ray',
  'Renet, Temporal Apprentice',
  'Retro-Mutation',
  'Return to the Sewers',
  'Rhythm of the Wild',
  'Rock Soldiers',
  'Rocksteady, Crash Courser',
  'Sally Pride, Lioness Leader',
  "Savanti Romero, Time's Exile",
  'Saved by the Shell',
  'Sewer-veillance Cam',
  'Shadowspear',
  'Shark Shredder, Killer Clone',
  "Shredder's Armor",
  "Shredder's Revenge",
  "Shredder's Technique",
  'Shredder, Unrelenting',
  'Silverclad Ferocidons',
  'Skateboard',
  'Slash, Reptile Rampager',
  'Slithering Cryptid',
  'South Wind Avatar',
  'Spicy Oatmeal Pizza',
  "Splinter's Technique",
  'Splinter, Hamato Yoshi',
  'Splinter, Radical Rat',
  'Squirrelanoids',
  'Stockman, Mad Fly-entist',
  'Stomped by the Foot',
  'Super Shredder',
  'Swamp',
  'Sword of Sinew and Steel',
  'TCRI Building',
  'Tainted Treats',
  'Technodrome',
  'Teleportation Circle',
  'Tenderize',
  'The Cloning of Shredder',
  'The Last Ronin',
  "The Last Ronin's Technique",
  'The Neutrinos',
  'The Ooze',
  'Tokka & Rahzar, Terrible Twos',
  'Transdimensional Bovine',
  'Triceraton Commander',
  'Trouble in Pairs',
  'Tunnel Rats',
  'Turncoat Kunoichi',
  'Turtle Blimp',
  'Turtle Lair',
  'Turtle Power!',
  'Turtle Van',
  'Turtles Forever',
  'Turtles in Time',
  "Umezawa's Jitte",
  'Undercity Sewers',
  'Underworld Breach',
  'Uneasy Alliance',
  'Utrom Scientists',
  'Venus, Torn Between Worlds',
  'Waves of Aggression',
  'Weather Maker',
  'West Wind Avatar',
  'Wingnut, Bat on the Belfry',
  'Zog, Triceraton Castaway',
  'Zoo Escapees',
] as const
